In [1]:
import pandas as pd
import numpy as np

In [2]:
data = 'https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv'

In [3]:
!wget $data

--2025-10-02 17:21:08--  https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv
185.199.109.133, 185.199.110.133, 185.199.111.133, ...tent.com)... 
connected. to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.133|:443... 
HTTP request sent, awaiting response... 200 OK
Length: 1475504 (1.4M) [text/plain]
Saving to: ‘data.csv.1’

data.csv.1          100%[===================>]   1.41M  6.46MB/s    in 0.2s    

2025-10-02 17:21:09 (6.46 MB/s) - ‘data.csv.1’ saved [1475504/1475504]



In [4]:
df = pd.read_csv('data.csv')

In [5]:
df.head()

Make       Model  Year             Engine Fuel Type  Engine HP  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0   
1  BMW    1 Series  2011  premium unleaded (required)      300.0   
2  BMW    1 Series  2011  premium unleaded (required)      300.0   
3  BMW    1 Series  2011  premium unleaded (required)      230.0   
4  BMW    1 Series  2011  premium unleaded (required)      230.0   

   Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0               6.0            MANUAL  rear wheel drive              2.0   
1               6.0            MANUAL  rear wheel drive              2.0   
2               6.0            MANUAL  rear wheel drive              2.0   
3               6.0            MANUAL  rear wheel drive              2.0   
4               6.0            MANUAL  rear wheel drive              2.0   

                         Market Category Vehicle Size Vehicle Style  \
0  Factory Tuner,Luxury,High-Performance      Compact         Coupe   
1                     Luxury,Performance      Compact   Convertible   
2                Luxury,High-Performance      Compact         Coupe   
3                     Luxury,Performance      Compact         Coupe   
4                                 Luxury      Compact   Convertible   

   highway MPG  city mpg  Popularity   MSRP  
0           26        19        3916  46135  
1           28        19        3916  40650  
2           28        20        3916  36350  
3           28        18        3916  29450  
4           28        18        3916  34500

In [6]:
df.columns = df.columns.str.lower().str.replace(' ', '_')

In [7]:
df.head()

make       model  year             engine_fuel_type  engine_hp  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0   
1  BMW    1 Series  2011  premium unleaded (required)      300.0   
2  BMW    1 Series  2011  premium unleaded (required)      300.0   
3  BMW    1 Series  2011  premium unleaded (required)      230.0   
4  BMW    1 Series  2011  premium unleaded (required)      230.0   

   engine_cylinders transmission_type     driven_wheels  number_of_doors  \
0               6.0            MANUAL  rear wheel drive              2.0   
1               6.0            MANUAL  rear wheel drive              2.0   
2               6.0            MANUAL  rear wheel drive              2.0   
3               6.0            MANUAL  rear wheel drive              2.0   
4               6.0            MANUAL  rear wheel drive              2.0   

                         market_category vehicle_size vehicle_style  \
0  Factory Tuner,Luxury,High-Performance      Compact         Coupe   
1                     Luxury,Performance      Compact   Convertible   
2                Luxury,High-Performance      Compact         Coupe   
3                     Luxury,Performance      Compact         Coupe   
4                                 Luxury      Compact   Convertible   

   highway_mpg  city_mpg  popularity   msrp  
0           26        19        3916  46135  
1           28        19        3916  40650  
2           28        20        3916  36350  
3           28        18        3916  29450  
4           28        18        3916  34500

In [8]:
df['make'].str.lower().str.replace(' ', '_')

0            bmw
1            bmw
2            bmw
3            bmw
4            bmw
          ...   
11909      acura
11910      acura
11911      acura
11912      acura
11913    lincoln
Name: make, Length: 11914, dtype: object

In [9]:
strings = list(df.dtypes[df.dtypes == 'object'].index)
strings

['make',
 'model',
 'engine_fuel_type',
 'transmission_type',
 'driven_wheels',
 'market_category',
 'vehicle_size',
 'vehicle_style']

In [10]:
for col in strings:
    df[col] = df[col].str.lower().str.replace(' ', '_')

In [11]:
df.dtypes

make                  object
model                 object
year                   int64
engine_fuel_type      object
engine_hp            float64
engine_cylinders     float64
transmission_type     object
driven_wheels         object
number_of_doors      float64
market_category       object
vehicle_size          object
vehicle_style         object
highway_mpg            int64
city_mpg               int64
popularity             int64
msrp                   int64
dtype: object

In [12]:
for col in df.columns:
    print(col)
    print(df[col].unique()[:5])
    print(df[col].nunique())
    print()

make
['bmw' 'audi' 'fiat' 'mercedes-benz' 'chrysler']
48

model
['1_series_m' '1_series' '100' '124_spider' '190-class']
914

year
[2011 2012 2013 1992 1993]
28

engine_fuel_type
['premium_unleaded_(required)' 'regular_unleaded'
 'premium_unleaded_(recommended)' 'flex-fuel_(unleaded/e85)' 'diesel']
10

engine_hp
[335. 300. 230. 320. 172.]
356

engine_cylinders
[ 6.  4.  5.  8. 12.]
9

transmission_type
['manual' 'automatic' 'automated_manual' 'direct_drive' 'unknown']
5

driven_wheels
['rear_wheel_drive' 'front_wheel_drive' 'all_wheel_drive'
 'four_wheel_drive']
4

number_of_doors
[ 2.  4.  3. nan]
3

market_category
['factory_tuner,luxury,high-performance' 'luxury,performance'
 'luxury,high-performance' 'luxury' 'performance']
71

vehicle_size
['compact' 'midsize' 'large']
3

vehicle_style
['coupe' 'convertible' 'sedan' 'wagon' '4dr_hatchback']
16

highway_mpg
[26 28 27 25 24]
59

city_mpg
[19 20 18 17 16]
69

popularity
[3916 3105  819  617 1013]
48

msrp
[46135 40650 36350 29450 345

In [13]:
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

In [14]:
sns.histplot(df.msrp[df.msrp < 100000], bins=50)

<Axes: xlabel='msrp', ylabel='Count'>

In [15]:
np.log([0 + 1, 1 + 1, 10 + 1, 1000 + 1, 100000 + 1])

array([ 0.        ,  0.69314718,  2.39789527,  6.90875478, 11.51293546])

In [16]:
np.log1p([0, 1, 10, 1000, 100000])

array([ 0.        ,  0.69314718,  2.39789527,  6.90875478, 11.51293546])

In [17]:
price_logs = np.log1p(df.msrp)

In [18]:
price_logs

0        10.739349
1        10.612779
2        10.500977
3        10.290483
4        10.448744
           ...    
11909    10.739024
11910    10.945018
11911    10.832122
11912    10.838031
11913    10.274913
Name: msrp, Length: 11914, dtype: float64

In [19]:
sns.histplot(price_logs, bins=50)

<Axes: xlabel='msrp', ylabel='Count'>

In [20]:
df.isnull().sum()

make                    0
model                   0
year                    0
engine_fuel_type        3
engine_hp              69
engine_cylinders       30
transmission_type       0
driven_wheels           0
number_of_doors         6
market_category      3742
vehicle_size            0
vehicle_style           0
highway_mpg             0
city_mpg                0
popularity              0
msrp                    0
dtype: int64

In [21]:
len(df)

11914

In [22]:
n = len(df)

n_val = int(n * 0.2)
n_test = n_val
n_train = n - n_val - n_test


In [23]:
n_val, n_test, n_train

(2382, 2382, 7150)

In [24]:
df.iloc[[10, 0, 3, 5]]

make       model  year             engine_fuel_type  engine_hp  \
10  bmw    1_series  2013  premium_unleaded_(required)      300.0   
0   bmw  1_series_m  2011  premium_unleaded_(required)      335.0   
3   bmw    1_series  2011  premium_unleaded_(required)      230.0   
5   bmw    1_series  2012  premium_unleaded_(required)      230.0   

    engine_cylinders transmission_type     driven_wheels  number_of_doors  \
10               6.0            manual  rear_wheel_drive              2.0   
0                6.0            manual  rear_wheel_drive              2.0   
3                6.0            manual  rear_wheel_drive              2.0   
5                6.0            manual  rear_wheel_drive              2.0   

                          market_category vehicle_size vehicle_style  \
10                luxury,high-performance      compact         coupe   
0   factory_tuner,luxury,high-performance      compact         coupe   
3                      luxury,performance      compact         coupe   
5                      luxury,performance      compact         coupe   

    highway_mpg  city_mpg  popularity   msrp  
10           28        20        3916  39600  
0            26        19        3916  46135  
3            28        18        3916  29450  
5            28        18        3916  31200

In [25]:
df_train = df.iloc[:n_train]
df_val = df.iloc[n_train:n_train+n_val]
df_test = df.iloc[n_train+n_val:]

In [26]:
df_train

make       model  year             engine_fuel_type  engine_hp  \
0         bmw  1_series_m  2011  premium_unleaded_(required)      335.0   
1         bmw    1_series  2011  premium_unleaded_(required)      300.0   
2         bmw    1_series  2011  premium_unleaded_(required)      300.0   
3         bmw    1_series  2011  premium_unleaded_(required)      230.0   
4         bmw    1_series  2011  premium_unleaded_(required)      230.0   
...       ...         ...   ...                          ...        ...   
7145    mazda      navajo  1994             regular_unleaded      160.0   
7146    mazda      navajo  1994             regular_unleaded      160.0   
7147  lincoln   navigator  2015             regular_unleaded      365.0   
7148  lincoln   navigator  2015             regular_unleaded      365.0   
7149  lincoln   navigator  2015             regular_unleaded      365.0   

      engine_cylinders transmission_type     driven_wheels  number_of_doors  \
0                  6.0            manual  rear_wheel_drive              2.0   
1                  6.0            manual  rear_wheel_drive              2.0   
2                  6.0            manual  rear_wheel_drive              2.0   
3                  6.0            manual  rear_wheel_drive              2.0   
4                  6.0            manual  rear_wheel_drive              2.0   
...                ...               ...               ...              ...   
7145               6.0            manual  four_wheel_drive              2.0   
7146               6.0            manual  four_wheel_drive              2.0   
7147               6.0         automatic  four_wheel_drive              4.0   
7148               6.0         automatic  four_wheel_drive              4.0   
7149               6.0         automatic  rear_wheel_drive              4.0   

                            market_category vehicle_size vehicle_style  \
0     factory_tuner,luxury,high-performance      compact         coupe   
1                        luxury,performance      compact   convertible   
2                   luxury,high-performance      compact         coupe   
3                        luxury,performance      compact         coupe   
4                                    luxury      compact   convertible   
...                                     ...          ...           ...   
7145                                    NaN      compact       2dr_suv   
7146                                    NaN      compact       2dr_suv   
7147                                 luxury        large       4dr_suv   
7148                                 luxury        large       4dr_suv   
7149                                 luxury        large       4dr_suv   

      highway_mpg  city_mpg  popularity   msrp  
0              26        19        3916  46135  
1              28        19        3916  40650  
2              28        20        3916  36350  
3              28        18        3916  29450  
4              28        18        3916  34500  
...           ...       ...         ...    ...  
7145           18        14         586   2000  
7146           18        14         586   2000  
7147           20        15          61  65055  
7148           19        15          61  67220  
7149           22        16          61  61480  

[7150 rows x 16 columns]

In [27]:
idx = np.arange(n)
idx

array([    0,     1,     2, ..., 11911, 11912, 11913])

In [28]:
np.random.seed(2)
np.random.shuffle(idx)

In [29]:
df_train = df.iloc[idx[:n_train]]
df_val = df.iloc[idx[n_train:n_train+n_val]]
df_test = df.iloc[idx[n_train+n_val:]]

In [30]:
df_train.head()

make    model  year          engine_fuel_type  engine_hp  \
2735    chevrolet   cobalt  2008          regular_unleaded      148.0   
6720       toyota   matrix  2012          regular_unleaded      132.0   
5878       subaru  impreza  2016          regular_unleaded      148.0   
11190  volkswagen  vanagon  1991          regular_unleaded       90.0   
4554         ford    f-150  2017  flex-fuel_(unleaded/e85)      385.0   

       engine_cylinders transmission_type      driven_wheels  number_of_doors  \
2735                4.0            manual  front_wheel_drive              2.0   
6720                4.0         automatic  front_wheel_drive              4.0   
5878                4.0         automatic    all_wheel_drive              4.0   
11190               4.0            manual   rear_wheel_drive              3.0   
4554                8.0         automatic   four_wheel_drive              4.0   

      market_category vehicle_size      vehicle_style  highway_mpg  city_mpg  \
2735              NaN      compact              coupe           33        24   
6720        hatchback      compact      4dr_hatchback           32        25   
5878        hatchback      compact      4dr_hatchback           37        28   
11190             NaN        large  passenger_minivan           18        16   
4554        flex_fuel        large    crew_cab_pickup           21        15   

       popularity   msrp  
2735         1385  14410  
6720         2031  19685  
5878          640  19795  
11190         873   2000  
4554         5657  56260

In [31]:
len(df_train), len(df_val), len(df_test)

(7150, 2382, 2382)

In [32]:
df_train = df_train.reset_index(drop=True)
df_val = df_val.reset_index(drop=True)
df_test = df_test.reset_index(drop=True)

In [33]:
y_train = np.log1p(df_train.msrp.values)
y_val = np.log1p(df_val.msrp.values)
y_test = np.log1p(df_test.msrp.values)

In [34]:
del df_train['msrp']
del df_val['msrp']
del df_test['msrp']

In [35]:
len(y_train)

7150

In [38]:
df_train.iloc[10]

make                                 rolls-royce
model                     phantom_drophead_coupe
year                                        2015
engine_fuel_type     premium_unleaded_(required)
engine_hp                                  453.0
engine_cylinders                            12.0
transmission_type                      automatic
driven_wheels                   rear_wheel_drive
number_of_doors                              2.0
market_category        exotic,luxury,performance
vehicle_size                               large
vehicle_style                        convertible
highway_mpg                                   19
city_mpg                                      11
popularity                                    86
Name: 10, dtype: object

In [44]:
xi = [453, 11, 86]

In [52]:
w0 = 7.17
w = [0.01, 0.04, 0.002]

In [50]:
def linear_regression(xi):
    n = len(xi)
    pred = w0

    for j in range(n):
        pred = pred + w[j] * xi[j]
    return pred

In [53]:
linear_regression(xi)

12.312

In [54]:
np.expm1(12.312)

np.float64(222347.2221101062)

In [56]:
np.log1p(222347.2221101062)

np.float64(12.312)

In [57]:
def dot(xi, w):
    n = len(xi)

    res = 0.0

    for j in range(n):
        res = res + xi[j] * w[j]
    return res

In [58]:
def linear_regression(xi):
    return w0 + dot(xi, w)

In [59]:
w_new = [w0] + w

In [60]:
w_new

[7.17, 0.01, 0.04, 0.002]

In [61]:
def linear_regression(xi):
    xi = [1] + xi 
    return dot(xi, w_new)

In [62]:
linear_regression(xi)

12.312

In [64]:
xi = [453, 11, 86]
w0 = 7.17
w = [0.01, 0.04, 0.002]

In [65]:
x1 = [1, 148, 22, 1385]
x2 = [1, 132, 25, 2031]
x10 = [1, 453, 11, 86]

In [66]:
X = [x1, x2, x10]
X

[[1, 148, 22, 1385], [1, 132, 25, 2031], [1, 453, 11, 86]]

In [69]:
X = np.array(X)
X

array([[   1,  148,   22, 1385],
       [   1,  132,   25, 2031],
       [   1,  453,   11,   86]])

In [70]:
X.dot(w_new)

array([12.3  , 13.552, 12.312])

In [71]:
def linear_regression(X):
    return X.dot(w_new)

In [72]:
linear_regression(X)

array([12.3  , 13.552, 12.312])